export const ADD_INGREDIENT = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENTS';
export const SET_INGREDIENT = 'SET_INGREDIENTS';
export const PURCHASE_BURGER_START='PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS='PURCHASE_BURGER_SUCCESS';